### ISSUE TITLE
No Heatmap is drawn

### ISSUE THREAD

**Issue by adamchui** [mikecunha/pygeo_heatmap#1]
I run the notebook once on my computer but find that the heatmap cannot be drawn on the map
so It could only show the shape file on the map.

![errror](https://user-images.githubusercontent.com/16800274/36928948-a880a20c-1ec5-11e8-8a53-48e73f9d693e.png)

Please help.

**Comment by hate5six** [comment]
I'm having the same issue

**Comment by maragard** [comment]
I've found that using `from folium import plugins` and constructing the heatmap with `plugins.HeatMap(...)` solves this issue.

**Comment by hugonbgg** [comment]
Need change this line: from:

hm_wide = HeatMap( zip(for_map.lat.values, for_map.lon.values, for_map.Amount.values),

hm_wide = HeatMap( list(zip(for_map.lat.values, for_map.lon.values, for_map.Amount.values)),

source: https://gis.stackexchange.com/questions/262137/folium-heat-maps

**Comment by mikecunha** [comment]
Thanks all, fixed now. Tested with folium 0.3.0 and 0.6.0
